### ISSUE TITLE
JS Loops

### ISSUE THREAD

**Issue by dree-max** [GitbookIO/javascript#146]
![screenbud-cbd1390c-fb74-4cfd-9abf-4f5360820a58](https://user-images.githubusercontent.com/62577261/141056172-83570d97-0937-47b1-ae86-bbceeb706bfc.png)
while learning JS, i ran into a small issue and im stuck . Any help rendered would be appreciated

**Comment by sabhinav10** [comment]
> ![screenbud-cbd1390c-fb74-4cfd-9abf-4f5360820a58](https://user-images.githubusercontent.com/62577261/141056172-83570d97-0937-47b1-ae86-bbceeb706bfc.png) while learning JS, i ran into a small issue and im stuck . Any help rendered would be appreciated

Hi ,In the for loop ,both initial and final value of i is inclusive: 
for(let i=5;i<=10;i++)
due to which **loop runs 6 times ** i think that might be the issue .Hope it helps.

**Comment by dree-max** [comment]
Hello, it still doesn't give me the required answer 
Thanks for the help though

**Comment by karthik123karthik** [comment]
try running  **i from 0 to n inside loop **  . I think it might work.

**Comment by dree-max** [comment]
still didnt work for me

**Comment by ghost** [comment]
Hi @dree-max, there's a super easy approach without loops if you want to... i.e. using ```.repeat()```.

You can simply solve this in 4 lines of code:

``` 
function scream(n) {
    let str = 'a'.repeat(n)
    console.log(str)
}

scream(10) 
```

Lemme know if you have any questions. Cheers :)

**Comment by dree-max** [comment]
Unfortunately this one has to have loops because it's what's been examined in this particular exercise!
Thank you for the other option though I tried it out and it works just fine

**Comment by VaibhavArora19** [comment]
You can Do it like this!
`function scream(n)
{
    let str = '';
    while(n--)
    {
        str +='a';
    }
    console.log(str);
}

scream(10);`

**Comment by VaibhavArora19** [comment]
You can do it like this!
```
function scream(n)
{
    let str = '';
    while(n--)
    {
        str +='a';
    }
    console.log(str);
}

scream(10);
```

**Comment by ghost** [comment]
Hello @ dree-max, you have already figured that out but still useful to give my two cents.

In Pseudocode, that problem would be solved like this:
```
 n = 5
 i = 0
 from i to n:
     //  do
````

In JavaScript, that would be solved like this:
```js
function scream(n) {
     let str = "";
     for (let i = 0; i<n; i++) 
          str = str + 'a';
     return str;
}

console.log(scream(2)); // aa
console.log(scream(5)); // aaaaa

````

**Comment by abhirajn** [comment]
@dree-max  run loop as  i=0 ; i < n; i++
this have to work

**Comment by SiyonaL** [comment]
function scream(n) {
     let str = "";
     for (let i = 0; i<n; i++) 
          str = str + 'a';
     return str;
}

console.log(scream(3)); // aaa
console.log(scream(5)); // aaaaa

//This will solve the issue. 
Happy to help :)

**Comment by Anshkaran7** [comment]
function scream(n) {
  return Array(n+1).join('a');
}

console.log(scream(3)); // aaa 
console.log(scream(5)); // aaaaa

Hey @dree-max , Easy approach without loops if you want to..(using an Array and then join it with 'a' as the separator.)

**Comment by vishal00923** [comment]
// simple solution with for loop

`function scream(n) {
   let str = '';
   for (let i = 0; i < n; ++i) {
      str += 'a';
   }
   
   return str;
}

console.log(scream(5));
console.log(scream(10));`
